import Menu from "./components/HeroSection/Menu";
import { MenuProvider } from "./context/MenuContext";
import "./globals.css";
import localFont from "next/font/local";

const Chillax = localFont({
  src: "../../public/fonts/Chillax-Variable.ttf",
  variable: "--font-chillax",
});

const Museo = localFont({
  src: "../../public/fonts/MuseoModerno-VariableFont_wght.ttf",
  variable: "--font-museo",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${Chillax.variable} ${Museo.variable}`}>
      <body className="antialiased">
        <MenuProvider>
          <main>
            <Menu />
            {children}
          </main>
        </MenuProvider>
      </body>
    </html>
  );
}
